### PR TITLE
Fix weapon ammo staying at one bullet

### PR DESCRIPTION
**Pull request by OfficiallyM**
Fix for ammo not dropping below one bullet

### CODE REVIEW

**Comment by phumberdroz** [comment]
Could you help me reproduce the issue before and after the fix?

**Comment by xenfovn** [comment]
thit shit bro , u cant use stugun with code

**Comment by Holidayy95** [comment]
yeah this breaks the stungun

**Comment by zfbx** [comment]
This also re-enables the stock action where when you run out of ammo it puts the gun away. which means you have to put the gun away again for the inventories sake then try and bring it out again and reload it

**Pull request closed without merging**
