### PR TITLE
Setup the ability to limit the maximum number of rounds that can be loaded into a firearm.

### PR DESCRIPTION
**Pull request by r0adra93**
**Describe Pull request**

This feature creates the ability to limit firearms to a maximum reload value that can be setup in the config file.

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes] (Be honest)
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]

### CODE REVIEW

**Comment by amantu-qbit** [comment]
Add the Ability to limit ammo for each Weapon. Global Limit is kind of Pointless cause Most people want to limit ammo per weapon not globally for all weapon.

**Comment by r0adra93** [comment]
> Add the Ability to limit ammo for each Weapon. Global Limit is kind of Pointless cause Most people want to limit ammo per weapon not globally for all weapon.

I added the ability to setup for each firearm type.

**Comment by r0adra93** [comment]
> Add the Ability to limit ammo for each Weapon. Global Limit is kind of Pointless cause Most people want to limit ammo per weapon not globally for all weapon.

I did as your recommended... do you plan on reviewing the PR?

**Comment by amantu-qbit** [comment]
Definitely. I'll review once I'm back home

**Comment by ChickenDipper1** [comment]
This does work, but if the clip has more bullets than you are allowed to put in the gun it will not let you load it at all.

Unsure why as using a simple if "total < 20 then"  on line 84 will work fine but applies to all guns, if you have for example 25 bullets in the gun and put in a 10 round clip and you have the limit at 30 you can still load the clip but you will only get the 5 bullets from it.

**Review by Irishstevie — APPROVED** [review]
Needs branch Updated But other than that works as it should.

**Pull request closed without merging**
